Cargo.lock
Cargo.toml
src/main.rs
src/primes.rs

based on similar code from cirru_edn.rs .

defining types

---

Cargo.lock
Cargo.toml
calcit/calcit.cirru
calcit/compact.cirru
src/builtins.rs
src/builtins/meta.rs
src/call_stack.rs
src/data/edn.rs
src/main.rs
src/snapshot.rs

some of the code moved to https://github.com/Cirru/cirru-edn.rs/pull/6 .

upgrade to new EDN lib

---

Cargo.lock
Cargo.toml
package.json
src/builtins.rs
src/builtins/effects.rs
src/lib.rs
src/main.rs
src/program.rs

indented to be used in https://github.com/calcit-lang/calcit-paint .

refactor entry code for library usages

---

Cargo.lock
Cargo.toml
calcit/snapshots/test-map.cirru
package.json
ts-src/calcit.procs.ts
ts-src/js-list.ts
ts-src/js-map.ts

which caused problems in using merge.

fix equality checking in js-map

---

Cargo.lock
Cargo.toml
calcit/snapshots/test-string.cirru
package.json
src/builtins/strings.rs
ts-src/calcit.procs.ts

According to https://stackoverflow.com/questions/51982999/slice-a-string-containing-unicode-chars .

fix UTF8 string slice

---

Cargo.lock
Cargo.toml
package.json
src/bin/cr.rs
src/builtins/syntax.rs
src/lib.rs
src/runner/preprocess.rs
ts-src/calcit.procs.ts

According to https://github.com/calcit-lang/calcit_runner.rs/discussions/73 .

refactor warnings to block and emit errors file

---

calcit/snapshots/test.cirru
package.json
src/cirru/calcit-core.cirru
yarn.lock

vite not used in this test at current.

extend get for tuple

---

Cargo.lock
Cargo.toml
calcit/snapshots/test.cirru
package.json
src/cirru/calcit-core.cirru
ts-src/calcit.procs.ts

it has to support both:
- different semantics from `or` on detecting `nil` and `false`.
- variadic arguments.

fix implementation of either

---

Cargo.lock
Cargo.toml
package.json
src/bin/bundle_calcit.rs
src/bin/cr.rs
src/builtins.rs
src/builtins/ffi.rs
src/builtins/meta.rs
src/call_stack.rs
src/cli_args.rs
src/data/cirru.rs
src/snapshot.rs
ts-src/calcit.procs.ts
yarn.lock

related to https://github.com/Cirru/parser.rs/pull/10 .

upgrade parser

---

.gitignore
Cargo.lock
Cargo.toml
calcit/snapshots/test-string.cirru
src/builtins.rs
src/builtins/effects.rs
src/builtins/meta.rs
src/builtins/refs.rs
src/builtins/syntax.rs
src/call_stack.rs
src/codegen/emit_js.rs
src/codegen/emit_js/internal_states.rs
src/codegen/gen_ir.rs
src/data/cirru.rs
src/data/edn.rs
src/primes.rs
src/primes/syntax_name.rs
src/program.rs
src/runner.rs
src/runner/preprocess.rs
ts-src/js-cirru.ts

push EDN small step forward in handling edge cases where we may need to have tuple. this is an incomplete feature.

extend EDN to have some tuple syntax

---

Cargo.lock
Cargo.toml
src/bin/bundle_calcit.rs
src/bin/cr.rs
src/bin/injection/mod.rs
src/builtins.rs
src/builtins/effects.rs
src/builtins/meta.rs
src/builtins/refs.rs
src/builtins/strings.rs
src/builtins/syntax.rs
src/call_stack.rs
src/codegen/emit_js.rs
src/codegen/emit_js/internal_states.rs
src/codegen/gen_ir.rs
src/data/cirru.rs
src/data/edn.rs
src/lib.rs
src/primes.rs
src/program.rs
src/runner.rs
src/runner/preprocess.rs
src/snapshot.rs
src/util/string.rs

also changed ABI version due to EDN changes.

migrating to Box<str>

---

Cargo.lock
Cargo.toml
package.json
src/bin/cr.rs
src/bin/injection/mod.rs
src/builtins.rs
src/builtins/effects.rs
src/builtins/lists.rs
src/builtins/maps.rs
src/builtins/meta.rs
src/builtins/records.rs
src/builtins/refs.rs
src/builtins/strings.rs
src/builtins/syntax.rs
src/call_stack.rs
src/codegen/emit_js.rs
src/codegen/emit_js/gen_stack.rs
src/codegen/emit_js/internal_states.rs
src/codegen/gen_ir.rs
src/data/cirru.rs
src/data/edn.rs
src/lib.rs
src/primes.rs
src/program.rs
src/runner.rs
src/runner/preprocess.rs
src/snapshot.rs
src/util/string.rs
ts-src/calcit.procs.ts

not ideal result:
running `test.cirru`: 1260ms -> 1160 roughly.
Timegrass memory: 45.1M -> 46.5M roughly.

use Arc<str> for sharing string buf

---

Cargo.lock
Cargo.toml
calcit/test-string.cirru
package.json
src/bin/cr.rs
src/builtins/strings.rs
src/lib.rs
src/program.rs
src/runner/track.rs
src/util/string.rs
ts-src/calcit.procs.ts

also refactor entries passing...

take care of service code preprocessing during reloading

---

Cargo.lock
Cargo.toml
calcit/test-list.cirru
calcit/test-map.cirru
calcit/test-set.cirru
package.json
src/call_stack.rs
src/cirru/calcit-core.cirru
ts-src/calcit.procs.ts

reduce a bit the overhead of methods initialization when they are not really used.

unlink several boring methods

---

src/builtins.rs

add function &format-ternary-tree

---

Cargo.lock
Cargo.toml
calcit/test-js.cirru
package.json
ts-src/calcit-data.mts
ts-src/calcit.procs.mts
ts-src/custom-formatter.mts
ts-src/js-list.mts
ts-src/js-map.mts
ts-src/js-record.mts
ts-src/js-set.mts
ts-src/js-tuple.mts

disable js warning specifically for custom formatter.

refine logic for js data inside calcit data

---

Cargo.lock
Cargo.toml
calcit/test-string.cirru
package.json
ts-src/calcit.procs.mts
ts-src/js-cirru.mts
ts-src/js-primes.mts

based on https://github.com/Cirru/cirru-edn.rs/pull/25
optimal result for a HashMap is:
```cirru
{} (:a 1) (:a1 0) (:c 2)
:b $ [] 1 2
```

smarter edn format for sorting map fields

---

Cargo.lock
Cargo.toml
calcit/test-string.cirru
package.json
src/builtins.rs
src/builtins/meta.rs
src/builtins/refs.rs
src/primes.rs
src/runner.rs
ts-src/calcit-data.mts
ts-src/calcit.procs.mts

Rust uses `u8` for Hash, in JavaScript I was using `uint` but actually only to have `float`.

make sure thunk being called in reset

---

Cargo.lock
Cargo.toml
package.json
src/bin/bundle_calcit.rs
src/codegen/emit_js.rs
src/snapshot.rs
ts-src/calcit.procs.mts

turned `bundle_calcit` into a watcher. now it also generates `.compact-inc.cirru` on changes.

connect bundle_calcit to hot-swapping

---

Cargo.lock
Cargo.toml
package.json
src/bin/bundle_calcit.rs
src/bin/cr.rs
src/builtins/maps.rs
src/builtins/records.rs
src/call_stack.rs
src/codegen/gen_ir.rs
src/snapshot.rs
ts-src/calcit.procs.mts

Based on https://github.com/Cirru/cirru-edn.rs/pull/27 .

update edn to use new APIs

---

Cargo.lock
Cargo.toml
package.json
src/bin/cr.rs
src/snapshot.rs
ts-src/calcit.procs.mts

the problem: self recursion in converting EDN data into `ChangesDict`, eats whole CPU, and hot swapping totally broken...

fix missing edn implementation for ChangesDict

---

Cargo.lock
Cargo.toml
package.json
src/builtins/meta.rs
ts-src/calcit.procs.mts
yarn.lock

fixed in https://github.com/calcit-lang/ternary-tree.rs/commit/a3db224119a5aa8ed3265b708c6265cd38a21d4e .

fixes error in butlast

---

src/builtins/meta.rs
src/builtins/refs.rs
src/builtins/syntax.rs
src/codegen/emit_js/gen_stack.rs
src/primes.rs

inspired https://www.slideshare.net/mitsunorikomatsu/performance-comparison-of-mutex-rwlock-and-atomic-types-in-rust .
no confirmed change in performance.

use some mutex

---

Cargo.lock
Cargo.toml
package.json
ts-src/calcit.procs.mts
yarn.lock

based on:
- https://github.com/Cirru/parser.rs/pull/27
- https://github.com/Cirru/parser.ts/pull/30

upgrade parser for escape r

---

Cargo.lock
Cargo.toml
calcit/test-js.cirru
calcit/test-list.cirru
package.json
src/bin/bundle_calcit.rs
src/bin/cr.rs
src/call_stack.rs
src/primes.rs
ts-src/calcit.procs.mts
ts-src/custom-formatter.mts
ts-src/js-cirru.mts
yarn.lock

still fixing https://github.com/calcit-lang/calcit/pull/183 .
displays:

console custom formatter for cirru-quote

---

Cargo.lock
Cargo.toml
calcit/test.cirru
package.json
src/primes.rs
ts-src/calcit.procs.mts

Duplication of ids brought troubles! Now an id looks like `gen_id_370_1673349465361`.

attach timestamp in generate-id! result

---

Cargo.lock
Cargo.toml
calcit/test-edn.cirru
calcit/test-js.cirru
package.json
src/builtins.rs
src/builtins/meta.rs
src/data.rs
src/primes/proc_name.rs
src/runner/preprocess.rs
ts-src/calcit.procs.mts

turning data into code back, targeting js generation from Cirru EDN files.

implement &data-to-code

---

.gitignore
Cargo.lock
Cargo.toml
README.md
package.json
src/bin/calcit_deps.rs
src/bin/injection/mod.rs
src/builtins/maps.rs
src/builtins/meta.rs
src/builtins/refs.rs
src/builtins/strings.rs
src/builtins/syntax.rs
src/call_stack.rs
src/codegen/emit_js.rs
src/codegen/emit_js/gen_stack.rs
src/codegen/emit_js/internal_states.rs
src/codegen/gen_ir.rs
src/data/cirru.rs
src/data/edn.rs
src/primes.rs
src/primes/proc_name.rs
src/primes/syntax_name.rs
src/program.rs
src/runner.rs
src/runner/preprocess.rs
yarn.lock

need more tricks in parser and edn libs, although I tried alreay.

random optimization related to memory

---

Cargo.lock
Cargo.toml
package.json
src/codegen/emit_js.rs

fixes
```cirru
:require
|@triadica/lagopus :as lagopus
lagopus/group
```

fix symbols escaping in js ns

---

.github/workflows/publish.yaml
.github/workflows/test.yaml
.gitignore
Cargo.lock
Cargo.toml
README.md
package.json
src/bin/bundle_calcit.rs
src/bin/calcit_deps.rs
src/bin/cr.rs
src/cli_args.rs

breaking refactor with argh

---

Cargo.lock
Cargo.toml
calcit/test-js.cirru
package.json
src/bin/calcit_deps.rs
src/bin/git/mod.rs
src/codegen/emit_js.rs
yarn.lock

experimental implementation of caps outdated

---

Cargo.lock
Cargo.toml
calcit/test-edn.cirru
package.json
src/builtins.rs
src/builtins/refs.rs
src/data/edn.rs
ts-src/calcit-data.mts
ts-src/calcit.procs.mts
ts-src/custom-formatter.mts
ts-src/js-cirru.mts
ts-src/js-primes.mts
ts-src/js-ref.mts
yarn.lock

based on https://github.com/Cirru/cirru-edn.rs/pull/44 . Atom inside EDN could be useful in some edge cases, and it does not break existed code.

extend edn to include atom
