README.md, src/cirru/calcit-core.cirru
`keys` shadows core definition `keys`... bad name.
=> fix invalid variable name of keys

Cargo.lock, Cargo.toml, package.json, src/codegen/emit_js.rs, src/codegen/gen_ir.rs, src/lib.rs, src/main.rs, src/primes.rs, src/program.rs, src/runner.rs, src/runner/preprocess.rs
After this change:
```cirru
:require
|dayjs :default dayjs
```
generates:
```js
import dayjs from "dayjs";
```
And previous `dayjs/@` has been removed.
=> partial refactor on import rules to support :default

Cargo.lock, Cargo.toml, calcit/snapshots/test.cirru, package.json, src/bin/bundle_calcit.rs, src/builtins/strings.rs, src/cirru/calcit-core.cirru, src/runner.rs
With `invoke`, we can now simulate ad-hoc polymorphism(in a very slow way...) in a dynamic manner. However, with this function, we don't have to implement a language-level ad-hoc polymorphism to make this Lisp really complicated.
Implementation of `invoke`:
```cirru
defn invoke (pair name & params)
assert "|method! applies on a pair, leading a record"
and (list? pair) (= 2 (count pair)) (record? (first pair))
assert "|method by string or keyword"
or (string? name) (keyword? name) (symbol? name)
let
proto $ nth pair 0
f $ &get proto name
assert "|expected function" (fn? f)
f (nth pair 1) & params
```
Define 2 pieces of data, with 2 records holding their methods
```cirru
defrecord %Num :inc :add :dec :show
def Num $ %{} %Num
:inc $ fn (x) $ [] Num (&+ x 1)
:dec $ fn (x) $ [] Num (&- x 1) …
```
=> add invoke; fix duplication evaluation of thunks

Cargo.lock, Cargo.toml, lib/calcit.procs.ts, package.json, src/codegen/emit_js.rs
with more detections, code from `case` and `cond` should try to use wrapped functions and `if`s for more readable js emission, rather then chaining ternary expressions.
=> neater js code for case/cond

Cargo.lock, Cargo.toml, calcit/snapshots/test-list.cirru, lib/calcit-data.ts, lib/calcit.procs.ts, lib/custom-formatter.ts, package.json
Add array mode operation in `concat` to reduce data conversion. Previously, combining `filter` and `concat` causes data conversion frequently.
Refactored implementation of `CrDataMap` trying to reduce cost in build tree. trade off is lookup algorithm efficiency become slower. It's supposed to gain lower memory occupation by using flat array here.
=> calcit-js: refactor Map internals; refine concat

Cargo.lock, Cargo.toml, calcit/snapshots/test-gynienic.cirru, calcit/snapshots/test-js.cirru, calcit/snapshots/test-record.cirru, calcit/snapshots/test.cirru, calcit/snapshots/util.cirru, lib/calcit-data.ts, lib/calcit.procs.ts, package.json, src/builtins.rs, src/builtins/lists.rs, src/builtins/maps.rs, src/builtins/meta.rs, src/builtins/records.rs, src/builtins/sets.rs, src/builtins/strings.rs, src/cirru/calcit-core.cirru, src/codegen/emit_js.rs, src/runner/preprocess.rs
For performance and consistency.
Also `nth` no longer support native JavaScript arrays. use `aget` instead.
=> refactor implementation for methods

Cargo.lock, Cargo.toml, calcit/snapshots/fibo.cirru, calcit/snapshots/test-list.cirru, calcit/snapshots/test-macro.cirru, calcit/snapshots/test-math.cirru, calcit/snapshots/test-record.cirru, calcit/snapshots/test-recursion.cirru, calcit/snapshots/test-string.cirru, calcit/snapshots/test.cirru, package.json, scripts/main.js, src/builtins.rs, src/builtins/maps.rs, src/builtins/math.rs, src/builtins/meta.rs, src/builtins/records.rs, src/builtins/sets.rs, src/builtins/strings.rs, src/cirru/calcit-core.cirru, src/codegen/emit_js.rs, src/codegen/emit_js/snippets.rs, src/runner/preprocess.rs, ts-src/calcit-data.ts, ts-src/calcit.procs.ts, ts-src/custom-formatter.ts, ts-src/js-cirru.ts, ts-src/js-record.ts
This PR contains many changes to APIs, which will probably break existing projects. Benefit is some quirky API names got unified. There are still some rough edges need to be polished in future versions of `0.4.x`.
Another change is the js emitted, some escaping names:
- `_AND_` -> `_$n_`
- `_COL_` -> `_$o_`
- `_BANG_` -> `_$x_`
- `_MAP_` -> `_$M_`
- `_LIST_` -> `_$L_`
=> Breaking refactor to unify APIs; starting 0.4.0-a1

Cargo.lock, Cargo.toml, package.json, src/codegen/emit_js.rs, src/codegen/gen_ir.rs, src/primes.rs, src/runner.rs, src/runner/preprocess.rs, ts-src/calcit.procs.ts
thunk are required since jsgen and irgen need raw code. there might be chance that thunk are called during preprocessing. in previous implementation, thunk are replaced after evaluated. now the thunk is retained. Might have performance costs since I don't master usages of `Box`.
=> attach value in thunk

Cargo.lock, Cargo.toml, package.json, src/bin/cr.rs, src/cli_args.rs, ts-src/calcit.procs.ts
new option `--watch-dir contents/` is used for watching changes from inlined assets. a cheaper way of shadow-cljs resource inlining.
`0.4.0` is released. the code is robust enough compared to `0.3.x`. Still have bugs though.
=> add --watch-dir ; refactor entry code a bit; ready for 0.4.0

Cargo.lock, Cargo.toml, package.json, ts-src/calcit-data.ts, ts-src/calcit.procs.ts
calcit has no solution providing hashes for plain js objects, but it's required when putting js data into a `CalcitSet`. So currently we got a dirty way.
=> some dirty fixes to js object hashing

Cargo.lock, Cargo.toml, calcit/snapshots/test-js.cirru, package.json, src/builtins.rs, src/builtins/meta.rs, src/codegen/emit_js.rs, src/codegen/emit_js/snippets.rs, src/runner/preprocess.rs, ts-src/calcit.procs.ts
Current syntax:
```cirru
defn f2 ()
hint-fn async
js-await $ f1
```
which is not optimal but should be enough.
Future support for arity checking during compiling is found to be hard to implement. So the `hint-fn` syntax for async might not be helpful for that. Future change will possibly break this.
=> try js codegen of async/await

Cargo.lock, Cargo.toml, package.json, src/codegen/emit_js/snippets.rs, ts-src/calcit.procs.ts
some chance the body will not return, which means that `ret_var` will not not assigned, which caused infinite loop.
for example:
```js
if ($calcit.empty_$q_($calcit.rest(xs))) {
console.log($calcit.printable("All finished.")); // <--------
} else {
ret_AUTO_2 =$calcit.recur($calcit.rest(xs), $calcit.inc(c))
}
if (ret_AUTO_2 instanceof $calcit.CalcitRecur) {
if (ret_AUTO_2.args.length !== 2) throw new Error('argument sizes do not match');
[ xs, c ] = ret_AUTO_2.args;
times_AUTO_3 += 1;
continue;
} else {
return ret_AUTO_2;
}
}
```
after this fix, `ret_AUTO_2` becomes a local variable, then it's okay.
=> refine js recursion implementation

Cargo.lock, Cargo.toml, package.json, src/codegen/emit_js.rs, ts-src/calcit.procs.ts
Fix redundant js reloads caused by https://github.com/calcit-lang/calcit_runner.rs/pull/89 .
=> enforce a stable order of generated keywords in js

Cargo.lock, Cargo.toml, src/bin/cr.rs, src/bin/injection/mod.rs, src/builtins/lists.rs, src/builtins/maps.rs, src/builtins/meta.rs, src/builtins/records.rs, src/builtins/refs.rs, src/builtins/sets.rs, src/builtins/strings.rs, src/builtins/syntax.rs, src/call_stack.rs, src/codegen/emit_js.rs, src/codegen/emit_js/gen_stack.rs, src/data/cirru.rs, src/data/edn.rs, src/lib.rs, src/primes.rs, src/runner.rs, src/runner/preprocess.rs, src/util.rs
migrating from https://docs.rs/im/15.0.0/im/ to https://docs.rs/rpds/0.10.0/rpds/ .
rpds has better maintenance. however, rpds has fewer methods implemented compared to im, so I have to add some very naive code related to list operations.
luckily, it becomes a litter faster after refactoring.
binary size went from 6128 to 5600. (not configuring features yet)
=> refactoring to rpds

Cargo.lock, Cargo.toml, package.json, src/bin/cr.rs, src/bin/injection/mod.rs, src/builtins/effects.rs, src/builtins/lists.rs, src/builtins/maps.rs, src/builtins/meta.rs, src/builtins/records.rs, src/builtins/refs.rs, src/builtins/sets.rs, src/builtins/strings.rs, src/builtins/syntax.rs, src/call_stack.rs, src/codegen/emit_js.rs, src/codegen/emit_js/gen_stack.rs, src/data/cirru.rs, src/data/edn.rs, src/lib.rs, src/primes.rs, src/runner.rs, src/runner/preprocess.rs, src/util.rs, ts-src/calcit.procs.ts
Based on work of https://github.com/calcit-lang/ternary-tree.rs .
=> migrating List to ternary-tree

Cargo.lock, Cargo.toml, package.json, src/codegen/emit_js.rs, src/codegen/emit_js/snippets.rs, ts-src/calcit-data.ts, ts-src/calcit.procs.ts, ts-src/custom-formatter.ts, ts-src/js-cirru.ts, ts-src/js-list.ts, ts-src/js-map.ts, ts-src/js-primes.ts, ts-src/js-record.ts
tested with Respo, the demo went from 60..90 to 70..110 relatively.
tested with Cumulo Timegrass, stable memory went from 25M to 18M, observed in activities monitor.
very rough comparison, but should reduce memory usages a bit. future improvements are requested...
=> Refactor to reduce memory occupation in js, but with regress on performance

Cargo.lock, Cargo.toml, src/bin/cr.rs, src/bin/injection/mod.rs, src/builtins/lists.rs, src/builtins/maps.rs, src/builtins/meta.rs, src/builtins/refs.rs, src/builtins/sets.rs, src/builtins/strings.rs, src/builtins/syntax.rs, src/call_stack.rs, src/codegen/emit_js.rs, src/codegen/emit_js/gen_stack.rs, src/codegen/gen_ir.rs, src/data/cirru.rs, src/data/edn.rs, src/lib.rs, src/primes.rs, src/primes/finger_list.rs, src/program.rs, src/runner.rs, src/runner/preprocess.rs, src/snapshot.rs
No doubt that finger tree has a better performance https://gist.github.com/jiyinyiyong/c5a9231e9d0e57060c302caac9a7bf86 . (Also it's a data structure that Haskell community proved to be able to be performant https://github.com/haskell-perf/sequences#results) .
Current implementation is slower in running default test,
```
167.32ms
181.128ms
188.221ms
189.993ms
179.551ms
194.768ms
186.948ms
180.29ms
174.392ms
203.554ms
```
compared to the result with ternary-tree:
```
165.206ms
177.051ms
197.866ms
181.556ms
195.387ms
199.398ms
178.274ms
173.925ms
175.909ms
186.421ms
```
partly caused by `Arc`. Profiling indicates that too much `Calcit` `Clone` happened after finger tree used. hope it become cheaper. Overall, finger tree is supposed to be more reliable than an unbalanced 2-3 tree.
=> Try FingerTree

src/builtins.rs, src/builtins/meta.rs
which displays internal structure of lists inside `im_ternary_tree`.
=> add function &format-ternary-tree

ts-src/calcit.procs.ts, ts-src/js-cirru.ts
[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.
=> refactor: replace deprecated String.prototype.substr()

Cargo.lock, Cargo.toml, calcit/debug/macro-ns.cirru, calcit/test-macro.cirru, calcit/test.cirru, package.json, src/builtins.rs, src/builtins/meta.rs, src/builtins/syntax.rs, src/cirru/calcit-core.cirru, src/codegen/emit_js.rs, src/codegen/emit_js/snippets.rs, src/primes/syntax_name.rs, src/runner.rs, src/runner/preprocess.rs, ts-src/calcit.procs.mts
调整以后, `gensym` 称为一个内置的语法, 可以得到解释器的 `file_ns` 状态, 在同一个 namespace 内部, 进行 symbol unique index 的自增. 并且 `file_ns` 在 preprocess 过程的传递也有调整.
测试无问题. 但是预处理的过程更复杂了, 细节的行为理解起来也更模糊了.
=> refactor gensym into syntax for stable index

Cargo.lock, Cargo.toml, calcit/test-js.cirru, package.json, src/bin/cr.rs, src/cli_args.rs, src/codegen/emit_js.rs, ts-src/calcit.procs.mts, yarn.lock
for a case like:
```cirru
; "a special case variable shadowing of `b`"
let
b -1
a $ loop
xs $ []
b 0
if (>= b 5) xs
recur (conj xs b) (inc b)
assert= a $ [] 0 1 2 3 4
assert= b -1
```
where `b` is defined both outside and inside, which reused the `return_label` of `loop` recursion. but actually it does not forward value, it only returns. the outer context should be unaware for code in bind function.
=> handle a special case of variable shadowing

src/bin/cr.rs, src/call_stack.rs, src/primes.rs
keywords are expected in http://repo.calcit-lang.org/calcit-error-viewer/ .
=> fix keywords in error snapshot

Cargo.lock, Cargo.toml, calcit/test-string.cirru, calcit/test.cirru, package.json, src/builtins.rs, src/builtins/meta.rs, src/codegen/emit_js.rs, src/data/cirru.rs, src/data/edn.rs, src/primes.rs, src/runner.rs, src/runner/preprocess.rs, ts-src/calcit-data.mts, ts-src/calcit.procs.mts, ts-src/js-cirru.mts, ts-src/js-primes.mts, yarn.lock
Since Cirru is a syntax for various DSLs, there are many cases we want to embed Cirru inside Calcit code to program other DSLs. To make it convenient and  more performance, `CirruQuote` variant is added into core.
New APIs:
- `cirru-quote` which is a special form are symbol reading phase,
- `parse-cirru-list`, which is previously `parse-cirru` that returns list, so it's breaking change,
- `parse-cirru`, which returns `CalcitCirruQuote` variant.
- `&cirru-quote:to-list`, which converts `CalcitCirruQuote` into Calcit list.
This is designed to simplify calcit-calx and calcit-wasmtime, and will probably break docs site.
=> add cirru-quote variant for better meta programming

Cargo.lock, Cargo.toml, calcit/test-cond.cirru, package.json, src/cirru/calcit-core.cirru, ts-src/calcit.procs.mts, yarn.lock
`tag-match` provides arms that matches `:tag` field in a HashMap and give it a new name:
```cirru
tag-match data
:a new-name-a
str-spaced "|found branch of" :a "|with value" $ :sth-of-a new-name-a
:b new-name-b
str-spaced "|found branch of" :b "|with value" $ :sth-of-b new-name-b
_ :other
```
`data` should match `map? data` with a field `:tag`, for example:
```cirru
{}
:tag :a
:sth-of-a "|some data belongs to a"
```
=> new macro tag-match

Cargo.lock, Cargo.toml, package.json, src/builtins/meta.rs, src/codegen/emit_js.rs, src/codegen/gen_ir.rs, src/primes.rs, src/runner.rs, src/runner/preprocess.rs, ts-src/calcit.procs.mts
`raw-code` type for storing variables like `js/window` that are emitted into code directly.
=> split out raw-code variant

Cargo.lock, Cargo.toml, package.json, src/bin/cr.rs, src/bin/injection/mod.rs, src/builtins.rs, src/builtins/lists.rs, src/builtins/meta.rs, src/builtins/refs.rs, src/builtins/syntax.rs, src/codegen/emit_js.rs, src/codegen/gen_ir.rs, src/data.rs, src/data/cirru.rs, src/data/edn.rs, src/lib.rs, src/primes.rs, src/primes/fns.rs, src/primes/symbol.rs, src/program.rs, src/runner.rs, src/runner/preprocess.rs
changed Calcit enum size from 80 bytes to 48 bytes.
https://gist.github.com/tiye/e91735c53b8afcb7ba587b03ca71e8ef
```
type: `calcit::Calcit`: 48 bytes, alignment: 8 bytes
discriminant: 1 bytes
variant `Tuple`: 47 bytes
padding: 7 bytes
field `.0`: 8 bytes, alignment: 8 bytes
field `.2`: 8 bytes
field `.1`: 24 bytes
variant `Recur`: 47 bytes
padding: 7 bytes
field `.0`: 40 bytes, alignment: 8 bytes
variant `List`: 47 bytes
padding: 7 bytes
field `.0`: 40 bytes, alignment: 8 bytes
variant `Set`: 47 bytes
padding: 7 bytes
field `.0`: 40 bytes, alignment: 8 bytes
variant `Map`: 47 bytes
padding: 7 bytes
field `.0`: 40 bytes, alignment: 8 bytes
variant `Record`: 47 bytes
padding: 7 bytes
field `.0`: 16 bytes, alignment: 8 bytes
field `.1`: 8 bytes
field `.2`: 8 bytes
field `.3`: 8 bytes …
```
=> Reduce enum size; optimize &str usages

Cargo.lock, Cargo.toml, package.json, src/bin/cr.rs, src/bin/injection/mod.rs, src/builtins.rs, src/builtins/lists.rs, src/builtins/maps.rs, src/builtins/meta.rs, src/builtins/records.rs, src/builtins/refs.rs, src/builtins/syntax.rs, src/calcit.rs, src/calcit/record.rs, src/call_stack.rs, src/codegen/emit_js.rs, src/data.rs, src/data/edn.rs, src/runner.rs, src/util/string.rs
based on https://github.com/Cirru/cirru-edn.rs/pull/41
=> support edn any-ref; change ABI version to 0.0.8

Cargo.lock, Cargo.toml, README.md, calcit/test-macro.cirru, package.json, src/bin/calcit_deps.rs, src/cirru/calcit-core.cirru, yarn.lock
add command on `caps`
- `caps download org/repo@tag`
add alias in Calcit
- `thread-first` for `->`
- `thread-last` for `->>`
- `thread-as` for `->%`
=> caps Download; thread-first aliases
